hangman_art = {0: ("   ",
                                   "   ",
                                   "   "),
                             1: (" o ",
                                   "   ",
                                   "   "),
                             2: (" o ",
                                   " | ",
                                   "   "),
                             3: (" o ",
                                   "/| ",
                                   "   "),
                             4: (" o ",
                                  "/|\\",
                                   "   "),
                              5: (" o ",
                                   "/|\\",
                                   "/  "),
                              6: (" o ",
                                   "/|\\",
                                   "/ \\")}

words = (
    "oso", "tigre", "león", "gato", "perro", "ratón", "jirafa", "elefante", "mono", "caballo",
    "zorro", "conejo", "vaca", "cerdo", "oveja", "lobo", "ardilla", "murciélago", "mapache", "nutria",
    "pato", "cisne", "águila", "halcón", "búho", "pájaro", "pingüino", "gallina", "gallo", "pavo",
    "pavo-real", "serpiente", "lagarto", "cocodrilo", "tortuga", "rana", "sapo", "pez", "delfín", "ballena",
    "tiburón", "foca", "pulpo", "calamar", "estrella-de-mar", "caballito-de-mar", "camaleón", "iguana", "flamenco", "abeja",
    "avispa", "mosca", "mosquito", "mariposa", "libélula", "cigarra", "grillo", "caracol", "lombriz", "cangrejo",
    "langosta", "gamba", "camarón", "almeja", "ostra", "medusa", "erizo-de-mar", "anémona", "coral", "escarabajo",
    "hormiga", "termita", "cucaracha", "araña", "escarabajo", "mantis", "escarabajo-pelotero", "puma", "pantera", "lince",
    "chita", "camello", "dromedario", "ciervo", "alce", "reno", "búfalo", "antílope", "cabra", "oveja",
    "asno", "mula", "ganso", "pato", "gallina", "cuervo", "gorrión", "golondrina", "loro", "canario",
    "avestruz", "emu", "koala", "canguro", "wombat", "ornitorrinco", "ratón-marsupial", "zarigüeya", "oso-hormiguero", "perezoso"
)
